import { Inter } from "next/font/google";
import "@styles/global.css";
import Nav from "@components/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-black">
        <main>
          <Nav />
          {children}
        </main>
      </body>
    </html>
  );
}
