import { Inter } from "next/font/google";
import "@styles/globals.css";
import Nav from "@components/Nav";
import {ThemeProvider} from "@components/MaterialTailwind"
import ToTop from "@components/ToTop";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Free Drinks",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-black">
        <main>
          <ThemeProvider>
          <Nav />
          {children}
          <ToTop/>
          </ThemeProvider>
        </main>
      </body>
    </html>
  );
}
